# Use postgres/example user/password credentials

version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rootroot
      POSTGRES_USER: myexample
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
